# Generated by Django 2.2 on 2022-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('project_id', models.CharField(max_length=20)),
                ('script_name', models.CharField(max_length=30)),
                ('is_thread', models.IntegerField(max_length=10)),
                ('retry_count', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DB_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('max_threads', models.IntegerField(max_length=20)),
                ('auto_host', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
