# Generated by Django 2.2 on 2022-01-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_case',
            name='is_thread',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='db_case',
            name='retry_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='db_project',
            name='max_threads',
            field=models.IntegerField(default=1),
        ),
    ]
