# Generated by Django 3.2 on 2022-01-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0002_auto_20220121_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='db_case',
            name='author',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db_case',
            name='script_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
