# Generated by Django 3.2 on 2022-01-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0003_auto_20220123_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tester',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
