# Generated by Django 2.2.27 on 2022-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0008_auto_20220218_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_list', models.CharField(max_length=30, null=True)),
                ('webhook', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
