# Generated by Django 2.2.27 on 2022-02-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0009_dbnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbnotice',
            name='notice_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbnotice',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
