# Generated by Django 2.2.27 on 2022-02-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0010_auto_20220219_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbnotice',
            name='notice_type',
            field=models.IntegerField(default=1),
        ),
    ]
