# Generated by Django 2.2 on 2022-02-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0011_auto_20220219_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('page_id', models.IntegerField()),
                ('element_location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DBPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_id', models.IntegerField()),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
