# Generated by Django 2.2 on 2022-02-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0012_dbelement_dbpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbelement',
            name='element_location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
