# Generated by Django 2.2.27 on 2022-02-27 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0014_auto_20220226_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbelement',
            name='loc_method',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
