# Generated by Django 2.2.27 on 2022-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0017_dbelement_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbelement',
            name='tag',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
